### ISSUE TITLE
真实数据数字和汉字对照表

### ISSUE THREAD

**Issue by ShuangtongLi** [ChenChengKuan/SeqGAN_tensorflow#11]
你好，我想看一下这个模型的生成效果。我注意到你的生成文件都是数字，那相应的汉字对照表能否发一下呢？谢谢～

**Comment by ChenChengKuan** [comment]
Hi
這個實驗本身並沒有生成中文，這裡做的是[paper](https://arxiv.org/pdf/1609.05473.pdf)裡的synthetic experiment，所以也沒對照表。

**Comment by letmeheard** [comment]
请问有人在这基础上做汉字语料生成吗~可以分享一下吗谢谢
