### ISSUE TITLE
关于SeqGAN的疑惑

### ISSUE THREAD

**Issue by Michellexmz** [ChenChengKuan/SeqGAN_tensorflow#4]
您好，我在学习研究您这个关于SeqGAN的实现，现在有一些疑惑，还请您指点一下。
代码里面的target_lstm是用于生成正样本和衡量Generator与oracle model的相似度的？如果我只是需要利用SeqGAN这个模型生成新的文本，那是否我可以不使用target_lstm，只需将我现有的文本作为正样本，将其放进模型中进行训练？
谢谢！

**Comment by ChenChengKuan** [comment]
1. 对 target lstm是用来衡量generator与orale model的相似度，他只是paper裡作者特别设计的一个评估方式
2. 对，把你的文本作为正样本即可

**Comment by Michellexmz** [comment]
好的，谢谢您的解答。
