### ISSUE TITLE
About real dataset

### ISSUE THREAD

**Issue by wyxcc** [ChenChengKuan/SeqGAN_tensorflow#6]
你好，我使用真实的语料集作为训练数据，但是发现生成文本的质量很不好，请问有什么在训练上的建议嘛？谢谢~

**Comment by ChenChengKuan** [comment]
seqgan的训练是相当不稳定的，目前关于怎麽让训练变好还是一个在研究中的课题。简单的方法我建议可以在pretrain多一点epoch。pretrain的效果好不好对seqgan影响很大。

**Comment by letmeheard** [comment]
@wyxcc hello你好，请问用真实的语料集作训练数据怎么进行，能不能指导一下呢，谢谢！

**Comment by wyxcc** [comment]
我是后来跑了那个texygen：https://github.com/geek-ai/Texygen/ 这里面支持跑真实语料集，中文的分好词了就行，你试试看~

**Comment by letmeheard** [comment]
好的！谢谢谢谢
